"""
ruler.py  —  GunBound transparent ruler overlay.

Loads assets/ruler.png (generated by tools/gen_ruler.py) and displays it as a
click-through overlay on top of the game window.

Requirements:
    pip install Pillow
    pip install pywin32  (optional, for auto-snap to game window)

Usage:
    python tools/ruler.py
    Escape or X to close.  R to re-snap.  Drag to reposition.
"""

import sys
import tkinter as tk
import ctypes
from pathlib import Path

from PIL import Image, ImageTk

# Allow running from any directory
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from gunbound.storage import ASSETS_DIR

# -- DPI awareness -------------------------------------------------------------
try:
    ctypes.windll.shcore.SetProcessDpiAwareness(2)
except Exception:
    try:
        ctypes.windll.user32.SetProcessDPIAware()
    except Exception:
        pass

# -- Configuration -------------------------------------------------------------
SCREEN_W          = 1600
SCREEN_H          = 1200
RULER_IMG         = str(ASSETS_DIR / "ruler.png")
GAME_WINDOW_TITLE = "GunBound"

# Color key: made transparent + click-through via -transparentcolor.
# Must NOT appear in ruler.png content.  RGB(1,1,1) = #010101.
BG_COLOR = "#010101"
BG_TUPLE = (1, 1, 1, 255)

BTN_FONT = ("Consolas", 12, "bold")

# -- pywin32 (optional) --------------------------------------------------------
try:
    import win32gui
    HAS_PYWIN32 = True
except ImportError:
    HAS_PYWIN32 = False


def find_game_window():
    if not HAS_PYWIN32:
        return None
    matches = []
    def _cb(hwnd, _):
        if win32gui.IsWindowVisible(hwnd):
            if GAME_WINDOW_TITLE.lower() in win32gui.GetWindowText(hwnd).lower():
                matches.append(hwnd)
    win32gui.EnumWindows(_cb, None)
    return matches[0] if matches else None


# -- App -----------------------------------------------------------------------

class RulerApp:
    def __init__(self, root):
        self.root = root
        self.root.title("GunBound Ruler")
        self.root.overrideredirect(True)
        self.root.geometry(f"{SCREEN_W}x{SCREEN_H}+0+0")
        self.root.configure(bg=BG_COLOR, bd=0, padx=0, pady=0)
        self.root.wm_attributes("-transparentcolor", BG_COLOR)
        self.root.wm_attributes("-topmost", True)

        # -- Load and composite PNG over BG_COLOR ------------------------------
        # Transparent PNG pixels -> BG_COLOR -> invisible + click-through.
        pil_img    = Image.open(RULER_IMG).convert("RGBA")
        bg_layer   = Image.new("RGBA", pil_img.size, BG_TUPLE)
        composited = Image.alpha_composite(bg_layer, pil_img)
        self._photo = ImageTk.PhotoImage(composited)

        # -- Canvas ------------------------------------------------------------
        self.canvas = tk.Canvas(
            root, width=SCREEN_W, height=SCREEN_H,
            bg=BG_COLOR, highlightthickness=0, bd=0,
        )
        self.canvas.place(x=0, y=0, width=SCREEN_W, height=SCREEN_H)
        self.canvas.create_image(0, 0, anchor="nw", image=self._photo)

        # -- Buttons -----------------------------------------------------------
        bsz, margin = 28, 6
        self._make_button(
            SCREEN_W - bsz - margin, margin, bsz,
            "X", "#8b0000", "#cc2222",
            lambda e: root.quit(),
        )
        self._make_button(
            SCREEN_W - 2 * (bsz + margin), margin, bsz,
            "R", "#003366", "#0055aa",
            lambda e: self.snap_to_game(),
        )

        # -- Drag --------------------------------------------------------------
        self._drag_ox = self._drag_oy = 0
        self.canvas.bind("<ButtonPress-1>", self._drag_start)
        self.canvas.bind("<B1-Motion>",     self._drag_move)
        self.canvas.bind("<Escape>",        lambda e: root.quit())
        self.canvas.focus_set()

        # -- Auto-snap after window is fully created ---------------------------
        root.update_idletasks()
        root.update()
        root.after(150, self.snap_to_game)

    # -- Snap ------------------------------------------------------------------

    def snap_to_game(self):
        self.root.update_idletasks()

        # Compensate for any internal border tkinter adds between root and canvas
        ox = self.canvas.winfo_rootx() - self.root.winfo_x()
        oy = self.canvas.winfo_rooty() - self.root.winfo_y()

        sw = self.root.winfo_screenwidth()
        sh = self.root.winfo_screenheight()
        cx = (sw - SCREEN_W) // 2 - ox
        cy = (sh - SCREEN_H) // 2 - oy + 25
        self.root.geometry(f"{SCREEN_W}x{SCREEN_H}+{cx}+{cy}")

    # -- Helpers ---------------------------------------------------------------

    def _make_button(self, x, y, size, symbol, bg, outline_color, command):
        c   = self.canvas
        tag = f"btn_{id(command)}"
        c.create_rectangle(x, y, x + size, y + size,
                           fill=bg, outline=outline_color, width=1, tags=tag)
        c.create_text(x + size // 2, y + size // 2,
                      text=symbol, fill="white", font=BTN_FONT, tags=tag)
        c.tag_bind(tag, "<Button-1>", command)

    def _drag_start(self, event):
        self._drag_ox = event.x_root - self.root.winfo_x()
        self._drag_oy = event.y_root - self.root.winfo_y()

    def _drag_move(self, event):
        x = event.x_root - self._drag_ox
        y = event.y_root - self._drag_oy
        self.root.geometry(f"{SCREEN_W}x{SCREEN_H}+{x}+{y}")


# -- Entry point ---------------------------------------------------------------

def main():
    if not Path(RULER_IMG).exists():
        print(f"Error: {RULER_IMG} not found.")
        print("Run first:  python tools/gen_ruler.py")
        return

    root = tk.Tk()
    app = RulerApp(root)
    root.mainloop()
    # Clear PhotoImage before destroying the Tcl interpreter to avoid
    # the "alloc: invalid block" Tcl/Tk memory warning on Windows.
    app._photo = None
    root.destroy()


if __name__ == "__main__":
    main()
